[[keymaps]]
command = "NextTrack"
key_sequence = ">"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "<"
[[keymaps]]
command = { SeekForward = { duration = 5 } }
key_sequence = "."
[[keymaps]]
command = { SeekBackward = {duration = 5 } }
key_sequence = ","
[[keymaps]]
command = "ShowActionsOnCurrentTrack"
key_sequence = "o"
