[main]
font=JetBrainsMono Nerd Font:size=12

[cursor]
style=beam
blink=no

[colors-dark]
# Alpha určuje průhlednost (1.0 je neprůhledné, 0.0 je úplně průhledné)
alpha=0.8
background=000000
foreground=dddddd

## Odpovídající barvy z kitty (pokud bys chtěl ladit)
regular0=000000  # black
regular1=cc0403  # red
regular2=19cb00  # green
regular3=cecb00  # yellow
regular4=0d73cc  # blue
regular5=cb1ed1  # magenta
regular6=0dcdcd  # cyan
regular7=dddddd  # white

bright0=767676   # brblack
bright1=f2201f   # brred
bright2=23fd00   # brgreen
bright3=fffd00   # bryellow
bright4=1a8fff   # brblue
bright5=fd28ff   # brmagenta
bright6=14ffff   # brcyan
bright7=ffffff   # brwhite

[key-bindings]
# Scrollování po řádcích (např. Shift+K a Shift+J)
scrollback-up-line=Shift+k
scrollback-down-line=Shift+j

# Scrollování po celých stránkách (např. Shift+PageUp/Down)
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down

# Skok na začátek/konec historie
scrollback-home=Control+Shift+Home
scrollback-end=Control+Shift+End

[scrollback]
lines=10000
multiplier=3.0

[mouse-bindings]
primary-paste=BTN_MIDDLE
select-begin=BTN_LEFT
select-begin-block=Control+BTN_LEFT
select-extend=BTN_RIGHT
select-extend-character-wise=Control+BTN_RIGHT
select-word=BTN_LEFT-2
select-word-whitespace=Control+BTN_LEFT-2
